In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0


## Introduction to Tensors


### Creating Tensors

In [2]:
# scalar
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
# get tensor back as python int
scaler.item()

7

In [5]:
scaler.size()

torch.Size([])

In [6]:
# vector
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [7]:
vector.size()

torch.Size([3])

In [8]:
vector.shape

torch.Size([3])

In [9]:
vector.dim()

1

In [10]:
# MATRIX
MATRIX = torch.tensor([[1, 2, 3],
                       [4, 5 ,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.size()

torch.Size([2, 3])

In [13]:
MATRIX[0]

tensor([1, 2, 3])

In [14]:
MATRIX[1]

tensor([4, 5, 6])

In [15]:
MATRIX[1][1]

tensor(5)

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5 ,6]],
                       [[7,8,9],
                        [10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [17]:
TENSOR.size()

torch.Size([2, 2, 3])

In [18]:
TENSOR.dim()

3

In [19]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [20]:
TENSOR[0][0][2]

tensor(3)

In [21]:
TENSOR[1][0][2]

tensor(9)

In [22]:
TENSOR2 = torch.tensor([
    [[[1, 2], [3, 4], [5, 6]],
     [[7, 8], [9, 10], [11, 12]]],
    [[[17, 18], [19, 20], [21, 22]],
     [[23, 24], [25, 26], [27, 28]]]
])
TENSOR2

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]],


        [[[17, 18],
          [19, 20],
          [21, 22]],

         [[23, 24],
          [25, 26],
          [27, 28]]]])

In [23]:
TENSOR2.size()

torch.Size([2, 2, 3, 2])

In [24]:
TENSOR2.ndim

4

In [25]:
# find 20
TENSOR2[1][0][1][1]

tensor(20)

In [26]:
# find 4
TENSOR2[0][0][1][1]

tensor(4)

### Random Tensors

In [27]:
# Create a random tensor of size (5, 3)
random_tensor = torch.randn(5, 3)
print(random_tensor)

tensor([[-0.8447,  1.6620,  1.8261],
        [ 0.0339,  0.7273, -0.1048],
        [-0.2689, -1.3209, -0.0209],
        [ 0.9625, -0.5756,  0.3496],
        [ 1.9493, -2.2126, -0.5677]])


In [28]:
random_tensor.ndim

2

In [29]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [30]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros_like_random_tensor = torch.zeros_like(random_tensor)
ones_like_random_tensor = torch.ones_like(random_tensor)

In [32]:
zeros_like_random_tensor, ones_like_random_tensor

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [33]:
import numpy as np
print(np.__version__)


2.4.1


In [34]:
%pip install numpy



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
